ALTER TABLE "EmailLoginToken"
ADD COLUMN "attemptCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "lastAttemptAt" TIMESTAMP(3),
ADD COLUMN "invalidatedAt" TIMESTAMP(3);

ALTER TABLE "AuthSession"
ADD COLUMN "lastSeenAt" TIMESTAMP(3);
