import { HazardObservation } from "../lib/types";
import { Hammer, Zap, Wrench, User, Copy, Check } from "lucide-react";
import { useState } from "react";

const TRADE_CONFIG: Record<string, { label: string; icon: React.ElementType; color: string; bg: string; description: string }> = {
  "general-contractor": {
    label: "General Contractor",
    icon: Hammer,
    color: "text-blue-700",
    bg: "bg-blue-50 border-blue-200",
    description: "Structural modifications, stair rails, doorway widening, outdoor railing",
  },
  electrician: {
    label: "Electrician",
    icon: Zap,
    color: "text-amber-700",
    bg: "bg-amber-50 border-amber-200",
    description: "Outlet placement, dedicated circuits, lighting upgrades, switch placement",
  },
  plumber: {
    label: "Plumber",
    icon: Wrench,
    color: "text-cyan-700",
    bg: "bg-cyan-50 border-cyan-200",
    description: "Walk-in shower conversion, tub removal, grab bar backing installation",
  },
  handyman: {
    label: "Handyman",
    icon: User,
    color: "text-green-700",
    bg: "bg-green-50 border-green-200",
    description: "Grab bar installation, threshold ramps, non-structural modifications",
  },
};

interface ContractorScopeProps {
  observations: HazardObservation[];
}

export default function ContractorScope({ observations }: ContractorScopeProps) {
  const [copied, setCopied] = useState(false);

  const proJobs = observations.filter((o) => !o.isDIY && o.trade);

  const byTrade = proJobs.reduce<Record<string, HazardObservation[]>>((acc, obs) => {
    const t = obs.trade!;
    if (!acc[t]) acc[t] = [];
    acc[t].push(obs);
    return acc;
  }, {});

  const generateScopeText = () => {
    const lines: string[] = [
      "HOME SAFETY RENOVATION — SCOPE OF WORK",
      "=".repeat(45),
      "",
    ];
    Object.entries(byTrade).forEach(([trade, items]) => {
      const cfg = TRADE_CONFIG[trade];
      lines.push(`\n${cfg?.label.toUpperCase() ?? trade.toUpperCase()}`);
      lines.push("-".repeat(35));
      items.forEach((item, i) => {
        lines.push(`${i + 1}. ${item.location}: ${item.recommendation}`);
        lines.push(`   Est. Cost: $${item.costMin}–$${item.costMax}`);
        lines.push(`   Priority: ${item.urgency}`);
      });
    });
    lines.push("\nGenerated by HFE — Home Fall & Safety Evaluator");
    return lines.join("\n");
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateScopeText()).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (proJobs.length === 0) {
    return (
      <div className="bg-white border border-warm-200 rounded-2xl p-6 shadow-sm text-center py-10 text-warm-400">
        <Hammer className="w-10 h-10 mx-auto mb-3" />
        <p>No professional installation items identified — most fixes are DIY.</p>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Summary */}
      <div className="flex items-center justify-between">
        <p className="text-warm-500 text-sm">
          {proJobs.length} item{proJobs.length !== 1 ? "s" : ""} require professional installation across {Object.keys(byTrade).length} trade{Object.keys(byTrade).length !== 1 ? "s" : ""}
        </p>
        <button
          onClick={handleCopy}
          className="inline-flex items-center gap-1.5 py-2 px-4 text-xs bg-white border border-warm-200 text-warm-700 hover:bg-warm-50 rounded-xl font-medium transition-colors"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
          {copied ? "Copied!" : "Copy Scope"}
        </button>
      </div>

      {/* By trade */}
      {Object.entries(byTrade).map(([trade, items]) => {
        const cfg = TRADE_CONFIG[trade] ?? TRADE_CONFIG.handyman;
        const Icon = cfg.icon;
        const totalMin = items.reduce((s, i) => s + i.costMin, 0);
        const totalMax = items.reduce((s, i) => s + i.costMax, 0);

        return (
          <div key={trade} className={`border rounded-2xl p-6 shadow-sm ${cfg.bg}`}>
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Icon className={`w-5 h-5 ${cfg.color}`} />
                <h3 className={`font-semibold ${cfg.color}`}>{cfg.label}</h3>
              </div>
              <span className="text-sm font-semibold text-warm-700">
                Est. ${totalMin.toLocaleString()}–${totalMax.toLocaleString()}
              </span>
            </div>
            <p className="text-xs text-warm-500 mb-4">{cfg.description}</p>

            <div className="space-y-3">
              {items.map((item, i) => (
                <div key={item.id} className="p-3 bg-white/70 rounded-xl border border-white/80">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-2">
                      <span className="text-xs font-bold text-warm-400 mt-0.5 shrink-0">{i + 1}.</span>
                      <div>
                        <p className="text-sm font-medium text-warm-900">{item.location}</p>
                        <p className="text-xs text-warm-500 mt-0.5">{item.recommendation}</p>
                      </div>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-xs font-semibold text-warm-700">
                        ${item.costMin}–${item.costMax}
                      </p>
                      <span
                        className={`text-[10px] font-medium ${
                          item.urgency === "immediate"
                            ? "text-red-600"
                            : item.urgency === "30-days"
                            ? "text-amber-600"
                            : "text-warm-400"
                        }`}
                      >
                        {item.urgency}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        );
      })}

      <div className="p-4 bg-warm-100 border border-warm-200 rounded-xl">
        <p className="text-xs text-warm-500 leading-relaxed">
          <span className="text-warm-700 font-medium">How to use this scope:</span> Copy this document and share it with contractors when requesting quotes. Ask each contractor to provide itemized pricing for each line item. Get at least 3 quotes for any job over $500.
        </p>
      </div>
    </div>
  );
}
